name: Check Proto Files

on:
  push:
  workflow_run:
    workflows: ["Detect Proto Changes"]
    types:
      - completed

jobs:
  Detect-Proto-Changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install protobuf
        run: sudo apt install -y protobuf-compiler
    
      - name: my path
        run: pwd

      - name: Download Proto Files from Other Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # curl -L -O -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/karamjb/proto
          curl -L -O https://github.com/karamjb/proto/archive/refs/heads/main.zip
          unzip -q main.zip -d ./proto
          echo pwd
          pwd
          echo ls
          ls

      - name: Compile Protobuf Files
        run: |
          # Replace with the actual command to compile protobuf files

          cd /home/runner/work/base-repo/base-repo/proto/proto-main

          echo pwd
          pwd
          echo ls
          ls

          protoc -I=. --java_out=./ --java_opt="annotate_code" employee.proto

      - name: Compare Protobuf Files
        run: |
          # Replace with the appropriate comparison command for your files
          if diff -qs <(sort /home/runner/work/base-repo/base-repo/proto/proto-main/com/karam/proto/events/Employee.java) <(sort /home/runner/work/base-repo/base-repo/com/karam/proto/events/Employee.java); then
            echo "No changes detected in protobuf files"
          else
            echo "Changes detected in protobuf files"
            diff -y /home/runner/work/base-repo/base-repo/proto/proto-main/com/karam/proto/events/Employee.java.pb.meta /home/runner/work/base-repo/base-repo/com/karam/proto/events/Employee.java.pb.meta
            exit 1
            # Add any actions or commands you want to perform when changes are detected
          fi

